#!/usr/bin/env bash
# This script configure Nginx server so that /redirect_me is redirecting to
# another page, meanwhile, the main domain is still showing
# Hello World!

apt-get update -y && apt-get upgrade -y
apt-get install nginx -y
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
line="\\\\tlocation /redirect_me {\n\t\treturn 301 https://www.instagram.com;\n\t}"
sed -i "48i $line" /etc/nginx/sites-available/default
sudo service nginx restart
