#!/usr/bin/env bash
# This script configure Nginx server so that /redirect_me is redirecting to
# another page, meanwhile, the main domain is still showing
# Hello World!

apt-get update -y && apt-get upgrade -y
apt-get install nginx -y
sudo chown -R "$USER":"$USER" /var/www/html

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;^\/redirect_me\n\treturn 301 https:\/\/www.instagram.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
