#!/usr/bin/env bash
# This script configures my Nginx server to have a custom 404 page that contains the string

sudo apt-get update
sudo apt-get install -y nginx

# code to redirect a specific endpoint (eg: redirect /redirect_me to https://www.instagram.com)
echo "Hello World!" > /var/www/html/index.nginx-debian.html
line="\\\\tlocation /redirect_me {\n\t\treturn 301 https://www.instagram.com;\n\t}"
sudo sed -i "48i $line" /etc/nginx/sites-available/default

# code to create error page and add a redirect for error 404
mkdir -p /var/www/default
echo "Ceci n'est pas une page" > /var/www/default/404.html
line1="\\\tlocation = /404.html {\n\t\t root /var/www/default;\n\t}"
sed -i "29i $line1" /etc/nginx/sites-available/default
line2="\\\terror_page 404 /404.html;"
sudo sed -i "32i $line2" /etc/nginx/sites-available/default

# restart the server
sudo service nginx restart
