#!/usr/bin/env bash
# script configures the server with new and updated parameters

sudo apt-get update -y 
sudo apt-get upgrade -y
chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html

q='"'
host=$(hostname)
line3="\\\tadd_header X-Served-By $q$host$q;"
sed -i "24i $line3" /etc/nginx/sites-available/default

line="\\\tlocation /redirect_me {\n\t\treturn 301
