#!/usr/bin/env bash
# script configures HAproxy in a load balancer 

sudo apt-get update && apt-get upgrade -y
sudo apt-get -y install haproxy

# configuration
sudo chown -R $USER:$USER /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 137512-web-01 54.89.72.145:80 check\n\tserver 137512-web-02 34.232.69.249:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
