#!/usr/bin/env bash
# script configures HAproxy in a load balancer 

sudo apt-get update && apt-get upgrade -y
sudo apt-get -y install haproxy

# configuration
sudo chown -R $USER:$USER /etc/haproxy/haproxy.cfg
echo -e "\nfrontend web_frontend\n\tbind *:80\n\tdefault_backend web_backend" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend web_backend\n\tbalance roundrobin\n\tserver web01 34.234.204.233:80 check\n\tserver web02 34.232.69.249:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
