#!/usr/bin/python3
"""Script extends to export data in the JSON format"""

import json
import sys
import requests


if __name__ == '__main__':
    baseUrl = "https://jsonplaceholder.typicode.com/users"
    employeeId = sys.argv[1]
    url = baseUrl + "/" + employeeId

    # Get employee name
    response = requests.get(url)
    username = response.json().get('username')

    # Get data on the ToDo of the employee
    todoUrl = url + "/todos"
    response = requests.get(todoUrl)
    tasks = response.json()
