#!/usr/bin/env bash
# this script debugs nginx; to forcefully remove default file
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo rm /run/nginx.pid
