#!/usr/bin/env bash
# a script that uses ssh to conect to your server
# using the private key ~/.ssh/school with the user ubuntu
# Set the server hostname or IP address
SERVER="54.89.72.145"

# Set the private key file path
PRIVATE_KEY_FILE="~/.ssh/school"

# Set the SSH user
SSH_USER="ubuntu"

ssh -i ~/.ssh/school ubuntu@54.89.72.145
